name: Demo
on:
  push:
    branches:
      - main
jobs:
  setup:
    name: Setup - ${{ matrix.os }} - ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016, windows-latest] # tar is able to unzip on windows 2019 but not on 2016
        go-version: [1.15.13, 1.16] # 1.16 is cached why 1.15.13 is not
    steps:
    - name: Setup - ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Test go version
      run: go version