name: Demo
on:
  push:
    branches:
      - main
jobs:
  setup:
    name: Setup - ${{ matrix.os }} - ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2016, windows-latest]
        go-version: [1.15.13]
    steps:
    - name: Setup - ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}